### ISSUE TITLE
Document how to set up conda/python etc on apple silicon

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/HowTo#18]
This has been an issue in the team, and I've had questions from researchers. This page would be a nice place to document everything,

Any volunteers @neuroinformatics-unit/neuroinformatics-team?

**Comment by lauraporta** [comment]
I can help!

**Comment by alessandrofelder** [comment]
I would agree with this assessment.

**Comment by adamltyson** [comment]
I'll close. If anyone thinks there are specific issues we should document solutions to, feel free to reopen.
