### ISSUE TITLE
Start documenting repositories for data/resource sharing

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/HowTo#20]
Lots of people ask this, and I think it's only going to become more important:

Off the top of my head:

* http://www.brainimagelibrary.org/ - brain imaging data (e.g. brainsaw)
* https://idr.openmicroscopy.org/ - any microscopy
* https://www.ebi.ac.uk/bioimage-archive/ - any bioimage
* https://dandiarchive.org/ - neurophysiology
* https://nemoarchive.org/ - omics
* http://openneuro.org/ - BIDS datasets
* https://www.v2.opensourcebrain.org/ - any neuroscience data (the data itself must be hosted elsewhere though)
* https://crcns.org/ - comp neuro
* brainglobe - atlases
* addgene - plasmids etc
* GIN - anything
* UCL Figshare - anything UCL
* https://ebrains.eu/service/share-data - any neuro data?
* SWC globus - anything, but not that user friendly, nor disoverable

Maybe a table with relevant info (e.g. data types supported, max file sizes) and pros/cons?

**Comment by adamltyson** [comment]
@neuroinformatics-unit/neuroinformatics-team please add any more you know of. I'm sure more were mentioned at the neurodatashare meeting.

**Comment by adamltyson** [comment]
https://datadryad.org/stash - anything

**Comment by niksirbi** [comment]
* [Zenodo](https://zenodo.org/) - anything

**Comment by niksirbi** [comment]
Also, for discovering datasets (as opposed to sharing them), [Google Dataset Search](https://datasetsearch.research.google.com/) is great

**Comment by lauraporta** [comment]
Genomic resources (maybe they are too obvious??):
- https://flybase.org/ - fruitfly genomes
- https://www.ncbi.nlm.nih.gov/ - well known genomes data and tools

Connectome (EM)
- https://www.microns-explorer.org/ - layers 2/3 connectivity + cortical explorer 
- [fly connectome, long link!](https://fafb-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B123352%2C67682%2C3276%5D%2C%22crossSectionScale%22:8.693213417325518%2C%22projectionOrientation%22:%5B0%2C0.7071067690849304%2C0%2C0.7071067690849304%5D%2C%22projectionScale%22:55551.89880590369%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_orig%22%2C%22name%22:%22fafb_v14%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe%22%2C%22name%22:%22fafb_v14_clahe%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/elmr-data/FAFBNP.surf/mesh#type=mesh%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%2225%22%2C%2226%22%2C%2227%22%2C%2228%22%2C%2229%22%2C%223%22%2C%2230%22%2C%2231%22%2C%2232%22%2C%2233%22%2C%2234%22%2C%2235%22%2C%2236%22%2C%2237%22%2C%2238%22%2C%2239%22%2C%224%22%2C%2240%22%2C%2241%22%2C%2242%22%2C%2243%22%2C%2244%22%2C%2245%22%2C%2246%22%2C%2247%22%2C%2248%22%2C%2249%22%2C%225%22%2C%2250%22%2C%2251%22%2C%2252%22%2C%2253%22%2C%2254%22%2C%2255%22%2C%2256%22%2C%2257%22%2C%2258%22%2C%2259%22%2C%226%22%2C%2260%22%2C%2261%22%2C%2262%22%2C%2263%22%2C%2264%22%2C%2265%22%2C%2266%22%2C%2267%22%2C%2268%22%2C%2269%22%2C%227%22%2C%2270%22%2C%2271%22%2C%2272%22%2C%2273%22%2C%2274%22%2C%2275%22%2C%228%22%2C%229%22%5D%2C%22name%22:%22neuropil-regions-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22mesh%22%2C%22source%22:%22vtk://https://storage.googleapis.com/neuroglancer-fafb-data/elmr-data/FAFB.surf.vtk.gz%22%2C%22shader%22:%22void%20main%28%29%20%7B%5Cn%20%20emitRGBA%28vec4%281.0%2C%200.0%2C%200.0%2C%200.5%29%29%3B%5Cn%7D%5Cn%22%2C%22name%22:%22neuropil-full-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://fafb-ffn1-20190805/segmentation%22%2C%22segments%22:%5B%224613663523%22%5D%2C%22name%22:%22fafb-ffn1-20190805%22%7D%5D%2C%22showAxisLines%22:false%2C%22showSlices%22:false%2C%22layout%22:%22xy-3d%22%7D)

**Comment by adamltyson** [comment]
> Genomic resources (maybe they are too obvious??):

Not that obvious, I hadn't heard of them. 

I guess we should define what fields we want to support in this effort though. Where's the cutoff?

* SWC 
* Mouse/systems neuro
* All neuroscience

**Comment by alessandrofelder** [comment]
[Image Data Resource](https://idr.openmicroscopy.org/about/index.html)?

Agree about defining a cut-off!
At the risk of overengineering it, should we have two lists?
* a list of the key SWC-related things that we maintain, curate and recommend
* a list of the things we heard of once and might be nice, but we don't really know

**Comment by adamltyson** [comment]
Sounds good, maybe something like:
* Curated table of the main, SWC-relevant repositories, with pros/cons, feedback from researchers.
* A basic list of the others with any info we happen to have

The cut off could be something like "repositories an SWC researcher might use in the next 12 months"?

**Comment by adamltyson** [comment]
- https://neuromorpho.org/ - neuronal morphologies
- https://senselab.med.yale.edu/ModelDB/ - comp neuro models

**Comment by adamltyson** [comment]
Summarised in a spreadsheet: https://docs.google.com/spreadsheets/d/1r9BvJJz6vK2T7aK0rEtNVWolQx8cJ3DOMj1CZlBWQbY/edit?usp=sharing
