### ISSUE TITLE
Repurpose Data Analysis section

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/HowTo#33]
## The problem
The rationale for the "Data Analysis" section was the following:
- have sub-sections according to data type: Behaviour, Electrophysiology, Imaging, Histology
- subdivide each data type into tools, eg. SLEAP
- Under each tool document common issues we/others encounter and their solutions.

It is clear that this section hasn't been used at all for this purpose, and it's currently an empty husk.

## My idea
Instead of using this section for dumping multiple small issues with each tool, we can use it to publish long-form guides for specific analysis use cases. For example, pur "How to run pose estimation on the HPC" guide could be hosted here under "Behaviour".
If we do this, we should rename the section currently named as "Guides". If most things on this page end up being guides, it will be confusing. I'd rename it as "Open Science"

Thoughts @neuroinformatics-unit/neuroinformatics-team ?

**Comment by adamltyson** [comment]
>  If we do this, we should rename the section currently named as "Guides". If most things on this page end up being guides, it will be confusing. I'd rename it as "Open Science"

This is nice, "data analysis", "programming" and "open science" probably sums up the team's remit pretty well.

**Comment by adamltyson** [comment]
>I was already thinking of including a "Troubleshooting" heading at the end of each long-form guide, which we could keep updated as people report problems. We could also have a more "general" Troubleshooting section at the level of each data type, but I would not make those if they are empty. We can add them if/when the content emerges? 

Sounds good

**Comment by niksirbi** [comment]
I could tackle the re-organisation this Friday, unless something else comes up. We could also look at https://github.com/neuroinformatics-unit/HowTo/issues/8
